---
- hosts: localhost
  connection: local
  become: True
  gather_facts: False

  tasks:
    - name: Create security group
      local_action:
        module: ec2_group
        name: ep2
        description: Access to the Episode2 servers
        region: us-west-2
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
    
    - name: Launch instances
      local_action:
        module: ec2
        group: ep2
        aws_access_key: A******************
        aws_secret_key: s******************      
        instance_type: t2.micro
        wait: true
        region: us-west-2
        exact_count: 2
        count_tag:
          Name: Demo
        instance_tags:
          Name: Demo
      register: ec2

    - name: Add EP2 instances to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=ep2
      with_items: "{{ec2.instances}}"

    - name: Add tag to instances
      local_action: ec2_tag resource={{ item.id }} region=us-west-2 state=present
      with_items: "{{ec2.instances}}"
      args:
        tags:
          Name: EP2

    - name: Wait for SSH to come up
      local_action: wait_for
                    host= "{{ item['instances'][0]['public_ip'] }}" 
                    port=22 
                    delay=60 
                    timeout=320 
                    state=started
      with_items: "{{ec2.instances}}"
